### ISSUE TITLE
Change price range filter

### ISSUE THREAD

**Issue by inomag** [PG-App/nest-webapp#1]
![Screenshot (6)](https://user-images.githubusercontent.com/66073063/113263867-f3335a00-92ef-11eb-864a-ffbae86c959f.png)

Write price filter as:
`filter = { ...filter, { $and : [{ 'fee_min' : { $lte : maxPrice }}, { 'fee_max' : { $gte : minPrice }}]} }`

**Comment by Bucephalus-lgtm** [comment]
Thanks @inomag , you made our life so easy! This is appreciable! Regards :)
